options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #CACHE
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      ['-c', 'docker pull $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest || exit 0']
    id: Cache
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Get Key
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        echo $(gcloud secrets versions access latest --secret="meilisearch_master_key") > /workspace/key.txt

  - id: Extract Key
    name: 'python'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        key=$(cat /workspace/key.txt)
        k=$(curl --location --request GET '$_NEXT_PUBLIC_MEILISEARCH_HOST_KEY/keys?limit=1' --header 'Content-Type: application/json' --header "Authorization: Bearer ${key}" --data-raw '' | grep -oP '(?<="key":")[^"]*' | sed -n '1p')
        echo $k > /workspace/key.txt
        cat /workspace/key.txt

  # BUILD
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - |
        key=$(cat /workspace/key.txt)
        echo $key
        docker build -t $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA -t $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest --cache-from $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest . -f Dockerfile.alfred-fe --build-arg _NEXT_PUBLIC_HOST_API_KEY=$_NEXT_PUBLIC_HOST_API_KEY --build-arg _NEXT_PUBLIC_MEILISEARCH_HOST_KEY=$_NEXT_PUBLIC_MEILISEARCH_HOST_KEY --build-arg _NEXT_PUBLIC_MEILISEARCH_API_KEY=$key --build-arg _NEXT_PUBLIC_POLYGON_USDC_ADDRESS=$_NEXT_PUBLIC_POLYGON_USDC_ADDRESS  --build-arg _NEXT_PUBLIC_ALFRED_FACTORY_ADDRESS=$_NEXT_PUBLIC_ALFRED_FACTORY_ADDRESS --build-arg _NEXT_PUBLIC_WORKFLOW_API_KEY=$_NEXT_PUBLIC_WORKFLOW_API_KEY --build-arg _NEXT_PUBLIC_CRYPTO_COMPARE_KEY=$_NEXT_PUBLIC_CRYPTO_COMPARE_KEY --build-arg _NEXT_PUBLIC_SOCKET_API_KEY=$_NEXT_PUBLIC_SOCKET_API_KEY --build-arg _NEXT_PUBLIC_POSTHOG_KEY=$_NEXT_PUBLIC_POSTHOG_KEY --build-arg _NEXT_PUBLIC_POSTHOG_HOST=$_NEXT_PUBLIC_POSTHOG_HOST --build-arg _NEXT_PUBLIC_MEASUREMENT_ID=$_NEXT_PUBLIC_MEASUREMENT_ID --build-arg _NEXT_PUBLIC_ARBITRUM_USDC_ADDRESS=$_NEXT_PUBLIC_ARBITRUM_USDC_ADDRESS --build-arg _NEXT_PUBLIC_ALFRED_ARBITRUM_FACTORY_ADDRESS=$_NEXT_PUBLIC_ALFRED_ARBITRUM_FACTORY_ADDRESS --build-arg _NEXT_PUBLIC_SENTRY_DSN=$_NEXT_PUBLIC_SENTRY_DSN
    id: Build

  # PUSH
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
    id: Push-Latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: updating MIGs default backend
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud compute instance-groups managed rolling-action replace ${_MIG_NAME} --region='${_MIG_REGION}' --max-surge=3 --max-unavailable=0
