options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #CACHE
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      ['-c', 'docker pull $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest || exit 0']
    id: Cache

  # BUILD
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '--cache-from'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - .
      - '-f'
      - Dockerfile.alfred-server
    id: Build

  # PUSH
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
    id: Push-latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: backend cloud run jobs update
    entrypoint: gcloud
    args: ['run','jobs','update','backend-prisma-migrate','--region',$_MIG_REGION]



  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: backend prisma migrate execute
    entrypoint: gcloud
    args: ['beta', 'run', 'jobs' ,'execute', 'backend-prisma-migrate','--region',$_MIG_REGION]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: updating MIGs default backend
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud compute instance-groups managed rolling-action replace ${_MIG_NAME} --region='${_MIG_REGION}' --max-surge=3 --max-unavailable=0