import { Stack, Typography, Grid } from '@mui/material';
import AddCardIcon from '@mui/icons-material/AddCard';
import LeaderboardIcon from '@mui/icons-material/Leaderboard';
export default function IntroducingBar() {
  return (
    <Grid container>
      <Stack
        direction="row"
        sx={{
          width: '100%',
          padding: { xs: '80px 20px', sm: '80px 80px', md: '80px 120px' },
          backgroundColor: 'background.paper',
          borderRadius: '6px',
          alignItems: 'center',
          justifyContent: 'space-evenly',
          mb: { xs: '-20px', md: '40px' },
          mt: { xs: '-40px', md: '0px' },
          flexDirection: { xs: 'column', lg: 'row' },
        }}
      >
        <Stack
          direction="column"
          sx={{ width: { xs: '100%', lg: '40%' }, mb: { xs: '20px', lg: '0px' } }}
        >
          <Typography
            sx={{
              textAlign: 'center',
              background: 'linear-gradient(180deg, #2D2D3D, #171722)',
              width: '21%',
              minWidth: '120px',
              padding: '7px 5px',
              color: '#F0D12F',
              borderRadius: '4px',
            }}
            variant="body2"
          >
            Introducing
          </Typography>
          <Typography
            sx={{ margin: '-50px 0 -60px 0', fontSize: '40px  !important' }}
            variant="h3"
            fontWeight="100"
          >
            <br /> Non-Custodial
          </Typography>
          <Typography sx={{ fontSize: '40px !important' }} variant="h3" fontWeight="bold">
            <br /> Copytrading.
          </Typography>
        </Stack>

        <Stack
          direction="row"
          justifyContent="space-between"
          sx={{ width: { xs: '100%', lg: '60%' } }}
        >
          <Stack direction="row" spacing={2} sx={{ width: { xs: '80%', md: '60%', lg: '45%' } }}>
            <AddCardIcon sx={{ color: 'text.primary', fontSize: '30px' }} />
            <Stack direction="column" spacing={2}>
              <Typography variant="h5" fontWeight="bold">
                Your Keys, Your Crypto
              </Typography>
              <Typography variant="body1">
                Alfred is 100% non-custodial, and your returns are effectively generated by you.
              </Typography>
            </Stack>
          </Stack>
          <Stack direction="row" spacing={2} sx={{ width: { xs: '80%', md: '60%', lg: '45%' } }}>
            <LeaderboardIcon sx={{ color: 'text.primary', fontSize: '30px' }} />
            <Stack direction="column" spacing={2}>
              <Typography variant="h5" fontWeight="bold">
                Mo' Money, No Problems
              </Typography>
              <Typography variant="body1">
                Copy the world's best traders, each with a unique strategy, risk level and
                transparent track record.
              </Typography>
            </Stack>
          </Stack>
        </Stack>
      </Stack>
    </Grid>
  );
}
